mode変更のロジックをmodeモデル内に移動
ShenQC-gif/co-card pull request #4
Opened 2020-12-01 22:20 UTC by ShenQC-gif

前回[Working]のPRでご指摘の通り、mode変更のロジックをmodeモデル内に移動しました。
こちらで方針良さそうでしょうか。

2020-12-02 19:41 UTC, acevif commented
@ShenQC-gif 

> 前回[Working]のPRでご指摘の通り、mode変更のロジックをmodeモデル内に移動しました。
> こちらで方針良さそうでしょうか。

nitpickですが、こういう会話的なのはPRのコメントに書くといいです。

PRの本文には、そのPRのcommitの論理的な意味(mode変更のロジックをmodeモデル内に移動 など)や、それを説明する補足、必要な資料、対応するissue(課題/チケットとも)などを書いていくといいです。
なければ空でも構いません。

2020-12-02 19:53 UTC, acevif commented
ブランチ名は https://qiita.com/homhom44/items/9f13c646fa2619ae63d0 にならって
feature/* などにするのがいい気がします

2020-12-02 20:00 UTC, acevif requested changes
レビューしました。
既にかなりいい感じですが、もうちょっと追求してみると勉強になると思います。
ここをちょっといい感じに突き詰めてみて、その後カスタムビューの切り出し or スキルシート作成などの次の作業にうつるといいと思います。

2020-12-02 20:00 UTC, acevif commented on co-card/Model/Mode.swift
> +        }
方向性は完全にあっています。

コードとしても悪くないと思いますが `mutating func`で書けたらその方がSwift的に自然かもです。
もしまだ試していないなら、コードのクオリティが向上する可能性があると思いますので、試してみていただけるといいと思います。

2020-12-02 20:00 UTC, acevif commented on co-card/Controller/MainViewController.swift
> +
こういう掃除をしていくの大事ですね!
IMOですが、コミットの意味が違うので分けるといいと思います。

2020-12-02 20:00 UTC, acevif commented on co-card/Controller/HomeViewController.swift
> +        mode = mode.previousMode
シンプルになりますね!

あまり仕事をしていないコードに思えるかもしれませんが、
View層やController層はイベントを伝えるだけのコード結構あるのでおかしいことではありません。
何もしていないように見えても、移譲と言って責任者を明確にするという仕事をしています。

2020-12-02 20:00 UTC, acevif commented on co-card/Model/Mode.swift
> +            return .VeryHard
VeryHardの「次」は存在するのでしょうか?
モデル層では、次が存在しないとしておいた方がいい気もします
プレゼンテーション層では、「次」が存在しない時は「次」ボタンがグレイアウトする(タップできないことが見た目でわかる)、とかだとユーザにとって親切かもしれません。

2020-12-03 23:36 UTC, ShenQC-gif commented on co-card/Model/Mode.swift
> +        }
ありがとうございます。試してみます。

2020-12-03 23:37 UTC, ShenQC-gif commented on co-card/Controller/MainViewController.swift
> +
パッと気付いたので忘れないうちに消してしまいましたが、仰る通りコミットの意味からは外れますね。
次から分けようと思います。

2020-12-03 23:39 UTC, ShenQC-gif commented on co-card/Controller/HomeViewController.swift
> +        mode = mode.previousMode
ありがとうございます。シンプルなので逆に不安でしたが、これはこれでしっかり役割があるように読み取ってもらえるので安心しました。勉強になります。

2020-12-03 23:41 UTC, ShenQC-gif commented on co-card/Model/Mode.swift
> +            return .VeryHard
VeryHardの次は存在しないですね。なので、enum Modeの状態の一つに、存在しないという状態を付け加えようかと思います。

2020-12-13 15:25 UTC, acevif commented on co-card/Model/Mode.swift
> +            return .VeryHard
@ShenQC-gif IMOですが、

そういう難易度は存在せず、「次の難易度」が存在しない場合があるだけですので、

* nextModeのswitch 文でreturn nil とする
* nextModeの戻り値の型はOptional<Mode>とする

のが良いでしょう。

2020-12-16 06:43 UTC, ShenQC-gif commented on co-card/Model/Mode.swift
> +            return .VeryHard
ありがとうございます。
別作業がひと段落しましたので、これから修正・改善していきます。

2020-12-16 08:30 UTC, ShenQC-gif commented
ブランチ名を変更しようとしましたが、調べたところPR出しながらの変更はできないようで、一旦このPRは閉じることとします。

2020-12-16 08:40 UTC, acevif commented
> ブランチ名を変更しようとしましたが、調べたところPR出しながらの変更はできないようで、一旦このPRは閉じることとします。

@ShenQC-gif ブランチ名の規約作るのは次からでも大丈夫ですよー

2020-12-16 08:53 UTC, ShenQC-gif commented
早速のご確認ありがとうございます。
別ブランチ作成してPR内でこちらをReferしようと考えていましたが、不便なのでこちらのブランチをReopenしてここで続けます。

2020-12-16 08:54 UTC, acevif commented
> @acevif 早速のご確認ありがとうございます。
> 
> 別ブランチ作成してPR内でこちらをReferしようと考えていましたが、不便なのでこちらのブランチをReopenしてここで続けます。

@ShenQC-gif はーい！

2020-12-19 02:35 UTC, ShenQC-gif commented on co-card/Model/Mode.swift
> +        }
特にfuncで渡す引数がないのであれば、varで書いた方が綺麗との記載(↓URLのコメント欄)があったのですが、mutating funcの方が分かりやすいでしょうか。

[https://qiita.com/cyan-drop/items/4db9d61f0794643eb996](url)

2020-12-22 20:20 UTC, acevif requested changes
iOSのMVCアーキテクチャの基本を重視してください。

2020-12-22 20:20 UTC, acevif commented on co-card/Controller/HomeViewController.swift
> +        if mode.nextMode == .VeryHard {
`.veryHard`が一番最高の難易度であるという知識は`Mode`型が知っているべき*責務*であるにもかかわらず、現在の書き方では HomeViewController が最高の`Mode`は何かという知識(すなわち判断するロジック)を持ち、`Mode`の責務がHomeViewControllerに漏れてしまっています。

`var hasNexMode: Bool` を作り、`if mode.hasNextMode {` のようにしてください。
慣れてくれば手を抜いて `mode.nextMode != nil` とか、`switch { case .some: 略...` とかでも良いのですが、まだ丁寧にやった方が良さそうです。

2020-12-22 20:20 UTC, acevif commented on co-card/Model/Mode.swift
> +        }
varとmutating funcは意味合いが違います。

mutating funcはstructそのものの値を変更するという意味があり、
varの場合は何らかのプロパティの値(上記URLの例ではString)に対応づけるという意味があります。

ここでは、`nextMode`は値の変更を意味しますから、mutating funcの方が適切です。

2020-12-22 20:20 UTC, acevif commented on co-card/Model/Mode.swift
> +    var nextMode: Mode! {
`Mode!` は危険です。

2020-12-22 20:20 UTC, acevif commented on co-card/Model/Mode.swift
> +    var previousMode: Mode! {
`Mode!` は基本的に避けるようにしましょう。

2020-12-22 20:20 UTC, acevif commented on co-card/Controller/HomeViewController.swift
>          }
この一連の画面変更処理は、`mode = mode.nextMode`の後にやるべきことです。

iOSにおける処理の流れは以下です:

1. Controllerは、ユーザの操作イベントを受けつけてModelにメッセージを伝える
2. Modelはメッセージに合わせて、Modelの責務としての状態変更を行う
3. ControllerはViewに新しいModelの状態を通知する
4. Viewは通知された新しいModelの状態を元にViewの状態を更新する

よって、画面の変更処理はModelの値を更新する `mode = mode.nextMode`の後に行われるべきです。

2020-12-22 20:20 UTC, acevif commented on co-card/Controller/HomeViewController.swift
> +            previousMode.isEnabled = true
この変数名は `previousModeButton` などにするとより良いですね。
ControllerはModel(Modeなど)とView(Buttonなど)を取り持つ存在ですので、それらがごっちゃにならないような変数名をつけましょう。

2020-12-29 06:45 UTC, acevif commented on co-card/Controller/HomeViewController.swift
> +    @IBOutlet var previousModeBtn: UIButton!
Btnなどの略称は使わない方がいいです。

かつてはプログラミングにおいて略語が多用されていましたが(画面が狭かったこと、1行の文字数が限られていたこと、インタプリタやコンパイラの性能が悪かったことなどが原因)、今日のプログラミングにおいては略語は忌避される傾向にあります。

普通の英語として通じるよく使われる略語（URL、DNS、WWWなど）を除いては、できるだけ使わないようにしましょう。

Swift のAPI Design Guidelinesにも以下のようにあります:
> Avoid abbreviations. Abbreviations, especially non-standard ones, are effectively terms-of-art, because understanding depends on correctly translating them into their non-abbreviated forms.
> https://swift.org/documentation/api-design-guidelines/#use-terminology-well

2021-01-09 05:26 UTC, acevif commented on co-card/Controller/HomeViewController.swift
>      @IBAction func nextMode(_: Any) {
→ `onNextModeButtonTapped`

2021-01-09 05:26 UTC, acevif commented on co-card/Controller/HomeViewController.swift
> +        mode = mode.next ?? mode
mode.nextMode()

2021-01-09 05:26 UTC, acevif commented on co-card/Controller/HomeViewController.swift
>          }
↑ここはモデル層の責務。

例えばmodeの中にうつす等が良い。具体的には mode.cardPerLine とやると4-6の数字が返ってくるように。

2021-01-09 05:26 UTC, acevif commented on co-card/Controller/HomeViewController.swift
>      func reflectMode() {
責務が明白になる名前づけにしましょう。
具体的には、Modelの状態の更新を受けてViewの表示を更新するという責務が明白になるよう、
`updateViews()` などにしましょう。

2021-01-09 05:26 UTC, acevif commented on co-card/Controller/HomeViewController.swift
> +        modeLabel.text = mode.title
ここらへんで、previousModeButtonとnextModeButtonなどのviewsの表示も更新しましょう。

元のコード:
```
        if mode.previous == nil{
            previousModeButton.isHidden = true
        }else {
            nextModeButton.isHidden = false
        }
```

↓
例えばこんなの
```
        previousModeButton.isHidden = !mode.previousModeExists
        nextModeButton.isHidden = !mode.nextModeExists
```

2021-01-09 05:26 UTC, acevif commented on co-card/Controller/MainViewController.swift
> +        if mode.title == "Very Hard" {
mode == .veryHard とかではダメですか?

2021-01-09 09:32 UTC, acevif commented on co-card/Model/Level.swift
> +        return "Level \(level)"
この文字列の生成は人間にレベルを伝えるためのものですよね。
であるとしたらModelではなくViewの責務です。

2021-01-09 09:32 UTC, acevif commented on co-card/Model/Level.swift
> +    func CurrentLevel() -> String{
nitpick(重箱の隅的な指摘)ですが、関数名は小文字で初めてcurrentLevel()としましょう。
大文字で始まるのは型の名前などです。

2021-01-09 09:32 UTC, acevif commented on co-card/Model/Level.swift
> +    var level = Int()
型を表すためなら `var level: Int` などですね!

2021-01-09 09:42 UTC, acevif reviewed
Modeがいい感じにロジックを含むようになってきていていいですね!
この調子です。

リファクタリングは大変ですが、リファクタリングによって設計が見えてくると、最初からいい設計で書けるようになります。

2021-01-17 12:22 UTC, acevif approved these changes
とても良いです。
ずいぶんコードが整理できてきたように思いますし、応用力もついてきたと思います。

「守破離」はご存知ですか? 「守破離」の「守」のスキルレベルを目指しつつ(そこにたどり着くまでにも多少時間がかかりますので)、ポートフォリオなどを充実させて実務にたどり着けることを目指していきましょう。

その先に「破」があります。つまり具体的にいうと、アーキテクチャに違反しても良い状況がどういう状況かわかるようになる段階が「破」です。

その次に「離」があるようですが、私もそこには到達していません。新しいアーキテクチャなどを考えられる人は「離」に当たると思います。

2021-01-17 12:22 UTC, acevif commented on co-card/View/Card.swift
> +class CardLabel{
IMHOですが、型の名前と合わせてファイル名もCardLabel.swiftとするとわかりやすいと思いました。

2021-01-17 12:22 UTC, acevif commented on co-card/Model/Score.swift
> +class Score {
このクラスの責務はなんですか?

もし現在のスコアの記録や加算が責務ならば、「CurrentScore」などのクラス名であると責務が明白になっていいと思います。

2021-01-17 12:22 UTC, acevif commented on co-card/Controller/GameoverViewController.swift
> +    @IBAction func onShareButtonTapped(_: Any) {
「onShareButtonTapped」とてもいいですね。
この部分を読むだけでこれが何か意味がわかります。

2021-01-17 12:22 UTC, acevif commented on co-card/Model/Mode.swift
> +    var title: String {
このtitleはModel層の責務ではないですね。
View層の責務なのでView層に移すといいと思います。

2021-06-01 22:55 UTC, merged